name: 'build-push'
on:
  workflow_dispatch

jobs:
  build_image:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - shell: bash
        run: |
          bash ./build.sh docker-action/template:${GITHUB_REF##*/}
